import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layouts/Header";


export const metadata: Metadata = {
  title: "Gowise",
  description: "Generated by create next app",
  icons: "/icon.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
